import type { AbnormalItemDefinition } from "../types";

/** The twelve authored anomaly items, grouped by their world axis and role. */
export const TASK4_ABNORMAL_ITEMS: AbnormalItemDefinition[] = [
  {
    id: "raw_meat_onigiri",
    kind: "abnormal",
    name: "生肉おにぎり",
    description: "赤い具材を白いご飯で包んだ、季節限定として陳列されているおにぎり。",
    price: 260,
    axis: "undead",
    anomalyRole: "base",
  },
  {
    id: "mask",
    kind: "abnormal",
    name: "マスク",
    description: "個包装された白いマスク。夜勤の人混みにも、見慣れない顔を隠すにも使える。",
    price: 140,
    axis: "undead",
    anomalyRole: "coexist",
  },
  {
    id: "counter_chicken",
    kind: "abnormal",
    name: "レジ横チキン",
    description: "レジ横の保温ケースに並ぶ、香ばしい衣のチキン。",
    price: 230,
    axis: "undead",
    anomalyRole: "runaway",
  },
  {
    id: "self_aware_battery",
    kind: "abnormal",
    name: "自我対応乾電池",
    description: "表示された容量の単位が、見るたびにわずかに変わる乾電池。",
    price: 480,
    axis: "machine",
    anomalyRole: "base",
  },
  {
    id: "shojo_manga",
    kind: "abnormal",
    name: "少女漫画",
    description: "配送箱の底から見つかった、感情の場面が多い少女漫画。",
    price: 520,
    axis: "machine",
    anomalyRole: "coexist",
  },
  {
    id: "precision_screwdriver",
    kind: "abnormal",
    name: "精密ドライバー",
    description: "細かな機械部品に合う、先端の精度を強調したドライバー。",
    price: 980,
    axis: "machine",
    anomalyRole: "runaway",
  },
  {
    id: "zero_gravity_cup_noodles",
    kind: "abnormal",
    name: "無重力カップ麺",
    description: "ふたを開けても湯気が落ちず、具材が底へ沈まないカップ麺。",
    price: 420,
    axis: "cosmic",
    anomalyRole: "base",
  },
  {
    id: "tourist_guide",
    kind: "abnormal",
    name: "観光ガイド",
    description: "地図の余白に、この町にはない星の記号が印刷された観光ガイド。",
    price: 680,
    axis: "cosmic",
    anomalyRole: "coexist",
  },
  {
    id: "mobile_power_bank",
    kind: "abnormal",
    name: "モバイル電源",
    description: "残量表示が夜空のように変化する、大容量のモバイル電源。",
    price: 1980,
    axis: "cosmic",
    anomalyRole: "runaway",
  },
  {
    id: "returning_soul_incense",
    kind: "abnormal",
    name: "帰魂線香",
    description: "火をつける前から帰り道の匂いがする、細身の線香。",
    price: 480,
    axis: "spirit",
    anomalyRole: "base",
  },
  {
    id: "photo_print_ticket",
    kind: "abnormal",
    name: "写真プリント券",
    description: "一枚の写真に、いないはずの人の居場所まで残せるプリント券。",
    price: 200,
    axis: "spirit",
    anomalyRole: "coexist",
  },
  {
    id: "purifying_salt",
    kind: "abnormal",
    name: "盛り塩",
    description: "白い粒を盛るだけで、境目のような跡が残る小袋の塩。",
    price: 110,
    axis: "spirit",
    anomalyRole: "runaway",
  },
];

export const ABNORMAL_ITEMS = TASK4_ABNORMAL_ITEMS;
export const ABNORMAL_ITEM_CATALOG = TASK4_ABNORMAL_ITEMS;
