import type { NewsArticle } from "../../domain";
import { leadingAxisCondition, newsArticle } from "./helpers";

export const TASK5_DAY5_NEWS: NewsArticle[] = [
  newsArticle({
    id: "news_d5_direct_convergence_refused",
    day: 5,
    role: "direct",
    notificationHeadline: "最後の特殊商品、販売完了",
    headline: "最後の一個、在庫のまま会計終了",
    body: "POSには販売拒否と在庫一個が同時に残り、閉店処理は完了しない。保存通知だけが販売完了を告げている。",
    conditions: { flag: { id: "convergence_refused" } },
    priority: 300,
    isFallback: false,
  }),
  newsArticle({
    id: "news_d5_direct_fallback",
    day: 5,
    role: "direct",
    notificationHeadline: "最後の一個、在庫一",
    headline: "閉店棚卸し、対象商品の在庫ゼロ",
    body: "現在の台帳は最後の商品が渡されたことだけを記録し、買った客の分類を空欄にした。レシートには客名ではなく、今夜の接客順が残る。",
    conditions: { true: true },
    priority: -100,
    isFallback: true,
  }),
  newsArticle({
    id: "news_d5_trend_undead",
    day: 5,
    role: "trend",
    notificationHeadline: "市の日の出、午前4時48分",
    headline: "市、夜明け放送を当面休止",
    body: "病院と事業所は脈のない夜勤者を通常勤務へ組み込み、交代時刻だけで一日を数え始めた。",
    conditions: leadingAxisCondition("undead"),
    priority: 200,
    exclusiveGroup: "d5_dominant_axis",
    isFallback: false,
  }),
  newsArticle({
    id: "news_d5_trend_machine",
    day: 5,
    role: "trend",
    notificationHeadline: "深夜店、有人レジの採用を継続",
    headline: "市内店舗、完全自動営業へ移行",
    body: "配送網と売場端末が在庫、勤務、入店順を自分で決め、人の確認欄は補足情報へ移された。",
    conditions: leadingAxisCondition("machine"),
    priority: 200,
    exclusiveGroup: "d5_dominant_axis",
    isFallback: false,
  }),
  newsArticle({
    id: "news_d5_trend_cosmic",
    day: 5,
    role: "trend",
    notificationHeadline: "最終バス、午前5時10分発",
    headline: "商店街発『最終便』、上空へ",
    body: "観光図は乗車案内へ書き換わり、町の入口には到着者と出発者を分ける光の列が伸びている。",
    conditions: leadingAxisCondition("cosmic"),
    priority: 200,
    exclusiveGroup: "d5_dominant_axis",
    isFallback: false,
  }),
  newsArticle({
    id: "news_d5_trend_spirit",
    day: 5,
    role: "trend",
    notificationHeadline: "合同供養、夜明けに終了",
    headline: "市の住民台帳、故人を現住所へ登録",
    body: "写真とガラスの反射を根拠に、返事のない住民にも住所が割り当てられた。町の境目は道路標識として残る。",
    conditions: leadingAxisCondition("spirit"),
    priority: 200,
    exclusiveGroup: "d5_dominant_axis",
    isFallback: false,
  }),
  newsArticle({
    id: "news_d5_trend_fallback",
    day: 5,
    role: "trend",
    notificationHeadline: "市の四制度、共通基準で統合",
    headline: "四つの基準、同じ時刻に正式版を発行",
    body: "病床、配送、到着場、戸籍の正式版が互いを上書きし、どれも最新版と表示される。単一の朝を示す記録はない。",
    conditions: { true: true },
    priority: -100,
    isFallback: true,
  }),
  newsArticle({
    id: "news_d5_discrepancy_receipt_count_fallback",
    day: 5,
    role: "discrepancy",
    notificationHeadline: "五夜の勤務、レシート二十九枚",
    headline: "POS保管庫、取引三十件を記録",
    body: "手元のレシートは二十九枚のままだが、現在のPOSには客のいない一件が追加されている。その一件の商品名は四つに切り替わり続ける。",
    conditions: { true: true },
    priority: -100,
    isFallback: true,
  }),
];

export const TASK5_NEWS_DAY5 = TASK5_DAY5_NEWS;
